#!/usr/bin/env bash
# This script displays a list of all currently running processes for all users, in a user-oriented format, showing the process hierarchy.

ps -eH -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

